### PR TITLE
Update .openpublishing.publish.config.json

### PR DESCRIPTION
**Pull request by vwxyzh**

### CODE REVIEW

**Comment by v-susu** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/vwxyzh-patch-1/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C11%5C14%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201711140709383009-21%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Rf3tSHiGRUEnrzOs1Gpo16gQo3gzXHXCzNh6KdhOM3k%3D&st=2017-11-14T08%3A44%3A31Z&se=2017-12-15T08%3A49%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/vwxyzh-patch-1/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[index.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/vwxyzh-patch-1/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/index?branch=pr-en-us-21) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C11%5C20%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201711200318056809-21%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NM5VqJJdywGsY6EGFuVqEPly58PTlc%2FPRJ%2Fnwv80NDM%3D&st=2017-11-20T04%3A56%3A25Z&se=2017-12-21T05%3A01%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/vwxyzh-patch-1/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[index.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/vwxyzh-patch-1/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/index?branch=pr-en-us-21) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C11%5C20%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201711200616164395-21%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=HgJ8xcTHGhTGeSJnvaS7213UsDYu%2FHWrBlG3yxL3%2Fzg%3D&st=2017-11-20T07%3A07%3A21Z&se=2017-12-21T07%3A12%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/vwxyzh-patch-1/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[index.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/vwxyzh-patch-1/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/index?branch=pr-en-us-21) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C11%5C22%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201711220604258768-21%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Ye04HLLyvp6X%2B30cAbOKaLsK4lSKsxzXOLNgZPZyqoo%3D&st=2017-11-22T07%3A52%3A31Z&se=2017-12-23T07%3A57%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/vwxyzh-patch-1/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[index.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/vwxyzh-patch-1/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/index?branch=pr-en-us-21) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C11%5C23%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201711230227264427-21%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CWwoSXuattnmvmKc3TEp4FRoW0CLkf8tJB68hiPP5IU%3D&st=2017-11-23T04%3A29%3A48Z&se=2017-12-24T04%3A34%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/vwxyzh-patch-1/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[index.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/vwxyzh-patch-1/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/index?branch=pr-en-us-21) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C11%5C23%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201711230611116448-21%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6%2FHSPzeFwWVrv9XJW%2FAAmVSSBz21sg%2FJLJ33mdGBZvw%3D&st=2017-11-23T08%3A53%3A52Z&se=2017-12-24T08%3A58%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
