### PR TITLE
Resolve syncing conflicts from master-sync-work to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from master-sync-work to master.

### CODE REVIEW

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\2tn2-s, target branch: master, target branch commit: a44234f381456a44963afaeacaa115280f66ff80, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C5%5C18%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201805181030315382-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=A81ECbcnC2BJDAoRvo%2Bh3ypjIPRgFzMvgv36ucqGzlA%3D&st=2018-05-18T10%3A36%3A41Z&se=2018-06-18T10%3A41%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\br4d-s, target branch: master, target branch commit: a44234f381456a44963afaeacaa115280f66ff80, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C5%5C29%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201805291844091775-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XQRV7Gok0xVhQmF0ykrMYHNAy78whMBErHEMZiiXclE%3D&st=2018-05-29T18%3A46%3A12Z&se=2018-06-29T18%3A51%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\nizb-s, target branch: master, target branch commit: a44234f381456a44963afaeacaa115280f66ff80, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C5%5C29%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201805292110486064-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=pmNF2YUGDkB7dLiHnHQaxbbQBpuEjAEhFyA8phfBtLE%3D&st=2018-05-29T21%3A13%3A09Z&se=2018-06-29T21%3A18%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\hpzk-s, target branch: master, target branch commit: a44234f381456a44963afaeacaa115280f66ff80, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C5%5C31%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201805311700141959-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xSnokaumwg0ZiMFnd3EZsLEX3TfjWdgQX1KFxlNinPY%3D&st=2018-05-31T17%3A02%3A01Z&se=2018-07-01T17%3A07%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\wzw1-s, target branch: master, target branch commit: a44234f381456a44963afaeacaa115280f66ff80, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C4%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806042200431923-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4eHhEAyPEvc20QPivz0j0U9bBRuUCRyX7x1EeP1MsBg%3D&st=2018-06-04T22%3A03%3A10Z&se=2018-07-05T22%3A08%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\wsrg-s, target branch: master, target branch commit: a44234f381456a44963afaeacaa115280f66ff80, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C5%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806050103486024-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2iEMFdEijcSzjM8x%2FJ4whY6ZwPMPGgH6dSiMo6N%2FJsc%3D&st=2018-06-05T01%3A05%3A53Z&se=2018-07-06T01%3A10%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\5e0s-s, target branch: master, target branch commit: a44234f381456a44963afaeacaa115280f66ff80, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C6%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806061659072262-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oSztVdAT8E9VsOo%2FSIjfy%2FCTm2OowGzUOky7jjIbZJo%3D&st=2018-06-06T17%3A00%3A47Z&se=2018-07-07T17%3A05%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\ck3k-s, target branch: master, target branch commit: a44234f381456a44963afaeacaa115280f66ff80, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C6%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806062119548931-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uiZVWUyHKhgiZSRP9LYqdv6mTjjZzCLLJdu9st2hY8M%3D&st=2018-06-06T21%3A22%3A26Z&se=2018-07-07T21%3A27%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\ptfq-s, target branch: master, target branch commit: a44234f381456a44963afaeacaa115280f66ff80, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C7%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806071602447885-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SCQHNCING6Mxw8%2F3pZQUr6wE3Fsfv9Qk6XnyXGHJH4c%3D&st=2018-06-07T16%3A04%3A44Z&se=2018-07-08T16%3A09%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\jqvh-s, target branch: master, target branch commit: a44234f381456a44963afaeacaa115280f66ff80, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C7%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806072028307677-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9El9dIV98efrLMSTKXz7WvdWU3o7%2FFcSy4%2F7U0DXCPA%3D&st=2018-06-07T20%3A30%3A50Z&se=2018-07-08T20%3A35%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\ygjl-s, target branch: master, target branch commit: a44234f381456a44963afaeacaa115280f66ff80, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C7%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806072314144056-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Z%2Bhhu3gpFlV3S%2FO%2Flov3JmZ6bSuZfxHDWVguAJYy3L4%3D&st=2018-06-07T23%3A16%3A07Z&se=2018-07-08T23%3A21%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/Microsoft.Azure.Management.ServiceFabric.Models.Cluster.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/Microsoft.Azure.Management.ServiceFabric.Models.Cluster.yml) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/microsoft.azure.management.servicefabric.models.cluster.-ctor?branch=pr-en-us-31) | [Details](#user-content-api%2FMicrosoft.Azure.Management.ServiceFabric.Models.Cluster.yml)
[api/Microsoft.Azure.Management.ServiceFabric.Models.ClusterUpdateParameters.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/Microsoft.Azure.Management.ServiceFabric.Models.ClusterUpdateParameters.yml) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/microsoft.azure.management.servicefabric.models.clusterupdateparameters?branch=pr-en-us-31) | [Details](#user-content-api%2FMicrosoft.Azure.Management.ServiceFabric.Models.ClusterUpdateParameters.yml)
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[api/overview/azure/containerinstance.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/containerinstance.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/containerinstance?branch=pr-en-us-31) |
[docs-ref-conceptual/index.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/docs-ref-conceptual/index.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/azure/index?branch=pr-en-us-31) |
[docs-ref-toc/top_level_toc.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/docs-ref-toc/top_level_toc.yml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/azure-dotnet.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/FrameworksIndex/azure-dotnet.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Channel/ITelemetry.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Channel/ITelemetry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Channel/ITelemetryChannel.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Channel/ITelemetryChannel.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Channel/InMemoryChannel.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Channel/InMemoryChannel.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Channel/Transmission.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Channel/Transmission.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/AvailabilityTelemetry.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/AvailabilityTelemetry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/DependencyTelemetry.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/DependencyTelemetry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/EventTelemetry.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/EventTelemetry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/ExceptionHandledAt.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/ExceptionHandledAt.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/ExceptionTelemetry.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/ExceptionTelemetry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/IJsonWriter.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/IJsonWriter.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/ISupportMetrics.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/ISupportMetrics.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/ISupportProperties.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/ISupportProperties.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/ISupportSampling.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/ISupportSampling.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/MetricTelemetry.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/MetricTelemetry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/PageViewTelemetry.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/PageViewTelemetry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/PerformanceCounterTelemetry.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/PerformanceCounterTelemetry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/RequestTelemetry.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/RequestTelemetry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/SessionState.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/SessionState.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/SessionStateTelemetry.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/SessionStateTelemetry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/SeverityLevel.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/SeverityLevel.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/TelemetryContext.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/TelemetryContext.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.DataContracts/TraceTelemetry.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.DataContracts/TraceTelemetry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId/ApplicationInsightsApplicationIdProvider.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId/ApplicationInsightsApplicationIdProvider.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId/DictionaryApplicationIdProvider.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId/DictionaryApplicationIdProvider.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing/DiagnosticsTelemetryModule.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing/DiagnosticsTelemetryModule.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing/Extensions.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing/Extensions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing/IHeartbeatPropertyManager.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing/IHeartbeatPropertyManager.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/CloudContext.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/CloudContext.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/ComponentContext.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/ComponentContext.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/DeviceContext.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/DeviceContext.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/HttpWebResponseWrapper.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/HttpWebResponseWrapper.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/InternalContext.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/InternalContext.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/JsonSerializer.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/JsonSerializer.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/LocationContext.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/LocationContext.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/OperationContext.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/OperationContext.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/OperationTelemetry.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/OperationTelemetry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/SessionContext.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/SessionContext.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TaskTimer.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TaskTimer.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TelemetryContextExtensions.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TelemetryContextExtensions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TelemetryDebugWriter.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TelemetryDebugWriter.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TelemetryModules.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TelemetryModules.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TelemetryProcessorChain.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TelemetryProcessorChain.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TelemetryProcessorChainBuilder.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TelemetryProcessorChainBuilder.xml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
<a name="api%2FMicrosoft.Azure.Management.ServiceFabric.Models.Cluster.yml"></a>
### [api/Microsoft.Azure.Management.ServiceFabric.Models.Cluster.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/Microsoft.Azure.Management.ServiceFabric.Models.Cluster.yml)
 - **Line 4**: **[Warning]** Invalid file link:(~/api/ClusterVersion.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/api/ClusterVersion.md).

<a name="api%2FMicrosoft.Azure.Management.ServiceFabric.Models.ClusterUpdateParameters.yml"></a>
### [api/Microsoft.Azure.Management.ServiceFabric.Models.ClusterUpdateParameters.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/Microsoft.Azure.Management.ServiceFabric.Models.ClusterUpdateParameters.yml)
 - **Line 4**: **[Warning]** Invalid file link:(~/api/ClusterVersion.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/api/ClusterVersion.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C8%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806080133549828-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=X9ZJbaNzkoOe1x7s6GD%2FtaOeY9jOG9a1JfvNbO4%2BlcI%3D&st=2018-06-08T02%3A54%3A52Z&se=2018-07-09T02%3A59%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
