### PR TITLE
Resolve syncing conflicts from master-sync-work to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from master-sync-work to master.

### CODE REVIEW

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\hymv-s, target branch: master, target branch commit: 01374199d3e4d03c18979612de5af0b72bb193bd, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C15%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806151459563241-36%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lpd3zMoHp2eMqwICh1GIiMjDu%2FOUPrNXWtjgQsBRBYs%3D&st=2018-06-15T15%3A01%3A47Z&se=2018-07-16T15%3A06%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\jdsb-s, target branch: master, target branch commit: 01374199d3e4d03c18979612de5af0b72bb193bd, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C15%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806151747559594-36%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lM5oOksfDaLWNKUsbRworcWkJJXzmmfCTmfJNqhpJ5g%3D&st=2018-06-15T17%3A49%3A17Z&se=2018-07-16T17%3A54%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\ymyj-s, target branch: master, target branch commit: 01374199d3e4d03c18979612de5af0b72bb193bd, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C27%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806271838589570-36%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PaQHDehvG5HwXC%2FmtpE%2Fw%2BRImp8sbbGKu5YWwx12gcY%3D&st=2018-06-27T18%3A42%3A18Z&se=2018-07-28T18%3A47%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\2zg3-s, target branch: master, target branch commit: 01374199d3e4d03c18979612de5af0b72bb193bd, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C27%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806271947007488-36%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rhtNCvuqoVPO7BBodZYny6q1mjW%2F9wM2Q6MDv038WSQ%3D&st=2018-06-27T19%3A50%3A02Z&se=2018-07-28T19%3A55%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\kblm-s, target branch: master, target branch commit: 01374199d3e4d03c18979612de5af0b72bb193bd, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C28%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806282306404793-36%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LQCZBLPwuIHNNKzvWmOHGFs58ANQ7UcSDTh1fn3HBCU%3D&st=2018-06-28T23%3A10%3A24Z&se=2018-07-29T23%3A15%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/Microsoft.Azure.NotificationHubs.NotificationHubDescription.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/Microsoft.Azure.NotificationHubs.NotificationHubDescription.yml) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/microsoft.azure.notificationhubs.notificationhubdescription.-ctor?branch=pr-en-us-36) | [Details](#user-content-api%2FMicrosoft.Azure.NotificationHubs.NotificationHubDescription.yml)
[api/Microsoft.Azure.NotificationHubs.Configuration.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/Microsoft.Azure.NotificationHubs.Configuration.yml) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/microsoft.azure.notificationhubs.configuration?branch=pr-en-us-36) | [Details](#user-content-api%2FMicrosoft.Azure.NotificationHubs.Configuration.yml)
[api/Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.yml) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/microsoft.azure.notificationhubs.configuration.sharedsecretelement.copyfrom?branch=pr-en-us-36) | [Details](#user-content-api%2FMicrosoft.Azure.NotificationHubs.Configuration.SharedSecretElement.yml)
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[_zip/msdn.4.5.2.zip](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/_zip/msdn.4.5.2.zip) | :white_check_mark:Succeeded | |
[api/overview/azure/activedirectory.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/activedirectory.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/activedirectory?branch=pr-en-us-36) |
[api/overview/azure/appservice.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/appservice.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/appservice?branch=pr-en-us-36) |
[api/overview/azure/automation.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/automation.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/automation?branch=pr-en-us-36) |
[api/overview/azure/batch.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/batch.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/batch?branch=pr-en-us-36) |
[api/overview/azure/billing.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/billing.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/billing?branch=pr-en-us-36) |
[api/overview/azure/cdn.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/cdn.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/cdn?branch=pr-en-us-36) |
[api/overview/azure/containerinstance.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/containerinstance.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/containerinstance?branch=pr-en-us-36) |
[api/overview/azure/cosmosdb.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/cosmosdb.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/cosmosdb?branch=pr-en-us-36) |
[api/overview/azure/data-factory.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/data-factory.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/data-factory?branch=pr-en-us-36) |
[api/overview/azure/data-lake-analytics.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/data-lake-analytics.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/data-lake-analytics?branch=pr-en-us-36) |
[api/overview/azure/data-lake-store.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/data-lake-store.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/data-lake-store?branch=pr-en-us-36) |
[api/overview/azure/dns.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/dns.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/dns?branch=pr-en-us-36) |
[api/overview/azure/event-hubs.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/event-hubs.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/event-hubs?branch=pr-en-us-36) |
[api/overview/azure/eventgrid.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/eventgrid.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/eventgrid?branch=pr-en-us-36) |
[api/overview/azure/hdinsight.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/hdinsight.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/hdinsight?branch=pr-en-us-36) |
[api/overview/azure/insights.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/insights.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/insights?branch=pr-en-us-36) |
[api/overview/azure/iot.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/iot.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/iot?branch=pr-en-us-36) |
[api/overview/azure/key-vault.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/key-vault.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/key-vault?branch=pr-en-us-36) |
[api/overview/azure/media-services.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/media-services.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/media-services?branch=pr-en-us-36) |
[api/overview/azure/mobile.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/mobile.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/mobile?branch=pr-en-us-36) |
[api/overview/azure/monitor.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/monitor.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/monitor?branch=pr-en-us-36) |
[api/overview/azure/mysql.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/mysql.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/mysql?branch=pr-en-us-36) |
[api/overview/azure/notification-hubs.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/notification-hubs.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/notification-hubs?branch=pr-en-us-36) |
[api/overview/azure/postgresql.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/postgresql.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/postgresql?branch=pr-en-us-36) |
[api/overview/azure/powerbi-embedded.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/powerbi-embedded.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/powerbi-embedded?branch=pr-en-us-36) |
[api/overview/azure/recovery-services.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/recovery-services.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/recovery-services?branch=pr-en-us-36) |
[api/overview/azure/redis-cache.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/redis-cache.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/redis-cache?branch=pr-en-us-36) |
[api/overview/azure/resource-manager.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/resource-manager.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/resource-manager?branch=pr-en-us-36) |
[api/overview/azure/search.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/search.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/search?branch=pr-en-us-36) |
[api/overview/azure/service-bus-relay.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/service-bus-relay.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/service-bus-relay?branch=pr-en-us-36) |
[api/overview/azure/service-bus.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/service-bus.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/service-bus?branch=pr-en-us-36) |
[api/overview/azure/service-fabric.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/service-fabric.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/service-fabric?branch=pr-en-us-36) |
[api/overview/azure/sql.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/sql.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/sql?branch=pr-en-us-36) |
[api/overview/azure/storage.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/storage.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/storage?branch=pr-en-us-36) |
[api/overview/azure/storsimple.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/storsimple.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/storsimple?branch=pr-en-us-36) |
[api/overview/azure/stream-analytics.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/stream-analytics.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/stream-analytics?branch=pr-en-us-36) |
[api/overview/azure/traffic-manager.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/traffic-manager.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/traffic-manager?branch=pr-en-us-36) |
[api/overview/azure/virtual-network.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/virtual-network.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/virtual-network?branch=pr-en-us-36) |
[api/overview/azure/virtualmachines.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/virtualmachines.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/virtualmachines?branch=pr-en-us-36) |
[docfx.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/docfx.json) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/dotnet-howto-migrate-to-vm.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/docs-ref-conceptual/dotnet-howto-migrate-to-vm.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/azure/dotnet-howto-migrate-to-vm?branch=pr-en-us-36) |
[docs-ref-conceptual/includes/create-sp.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/docs-ref-conceptual/includes/create-sp.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/azure/includes/create-sp?branch=pr-en-us-36) |
[msdn.4.5.2.zip](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/msdn.4.5.2.zip) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/azure-dotnet-preview.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/FrameworksIndex/azure-dotnet-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/azure-dotnet.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/FrameworksIndex/azure-dotnet.xml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
<a name="api%2FMicrosoft.Azure.NotificationHubs.NotificationHubDescription.yml"></a>
### [api/Microsoft.Azure.NotificationHubs.NotificationHubDescription.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/Microsoft.Azure.NotificationHubs.NotificationHubDescription.yml)
 - **[Warning]** 1 invalid cross reference(s) &quot;System.Net.HttpStatusCode.Forbidden&quot;.
 - **[Warning]** 1 invalid cross reference(s) &quot;System.Net.HttpStatusCode.Forbidden&quot;.

<a name="api%2FMicrosoft.Azure.NotificationHubs.Configuration.yml"></a>
### [api/Microsoft.Azure.NotificationHubs.Configuration.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/Microsoft.Azure.NotificationHubs.Configuration.yml)
 - **[Warning]** 1 invalid cross reference(s) &quot;Microsoft.Azure.NotificationHubs.TransportClientCredentialType.SharedSecret&quot;.

<a name="api%2FMicrosoft.Azure.NotificationHubs.Configuration.SharedSecretElement.yml"></a>
### [api/Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.yml)
 - **[Warning]** 1 invalid cross reference(s) &quot;Microsoft.Azure.NotificationHubs.TransportClientCredentialType.SharedSecret&quot;.

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C29%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806290322089550-36%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VMe9sNNs2UVdMHpyT%2Fm1%2BaUzQA36P0SLTwPmBQ9YMPU%3D&st=2018-06-29T04%3A33%3A15Z&se=2018-07-30T04%3A38%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
