### PR TITLE
Resolve syncing conflicts from master-sync-work to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from master-sync-work to master.

### CODE REVIEW

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[82a4eff](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/82a4effa719a213d0be8da781c4553ee62a2eef6)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[82a4eff](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/82a4effa719a213d0be8da781c4553ee62a2eef6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b230ff82)

<a id="b230ff82"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\ehrx-s, target branch: HEAD, target branch commit: 1b3083ce51e938978e6a52c25fce06f083aa623b, source commit: 82a4effa719a213d0be8da781c4553ee62a2eef6.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C3%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909031809173984-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=T5VQkkhl0akIXjFTtM7qCsqDEE8gTNs2qqsxpBB9vi0%3D&st=2019-09-03T18%3A11%3A46Z&se=2019-10-04T18%3A16%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[82a4eff](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/82a4effa719a213d0be8da781c4553ee62a2eef6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c463574f)

<a id="c463574f"></a>
###
 - **[Error]** `````Cannot merge commit 82a4effa719a213d0be8da781c4553ee62a2eef6 in branch master-sync-work of repository https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet into branch master (commit 76a172f36fafef2abbf95cfdf3a8cdc261eea89b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C4%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909040309110699-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Kttp%2FCmuZvYjRhb%2Bgo%2FMunDHAz5DYWidBBjbd8Q%2BvRY%3D&st=2019-09-04T03%3A04%3A22Z&se=2019-10-05T03%3A09%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[eb535fa](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/eb535fa6fb0f82197457b4acf56d09e81e246960)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/.openpublishing.publish.config.json) | :x:Error | | [Details](#user-content-d902ab53-8858e400)
[_dependentPackages/CommonPlugins/tools/SplitTOC.ps1](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/_dependentPackages/CommonPlugins/tools/SplitTOC.ps1) | :x:Error | | [Details](#user-content-f4dacc90-8858e400)
[]() | :x:Error | | [Details](#user-content-8858e400)

<a id="d902ab53-8858e400"></a>
### [.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/.openpublishing.publish.config.json)
 - **Line 80**: **[Error]** `````Failed to execute customized script at step docset_prebuild in docset e2eppe-azuredotnet. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins for docset e2eppe-azuredotnet step docset_prebuild or ask for help?in Docs Support teams channel. Please also include the build report and the following error code for our team to troubleshoot: 1`````
 - **Line 160**: **[Error]** `````Cannot find plug-in script _dependentPackages/CommonPlugins/tools/SplitTOC.ps1 at step docset_prebuild. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins or ask for help?in Docs Support teams channel.`````

<a id="f4dacc90-8858e400"></a>
### [_dependentPackages/CommonPlugins/tools/SplitTOC.ps1](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/_dependentPackages/CommonPlugins/tools/SplitTOC.ps1)
 - **Line 217**: **[Error]** `````Error happened when executing plug-in script _dependentPackages/CommonPlugins/tools/SplitTOC.ps1 at step docset_prebuild. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins or ask for help?in Docs Support teams channel. Please also include the build report and the following error code for our team to troubleshoot: 1`````

<a id="8858e400"></a>
###
 - **Line 138**: **[Error]** `````W:\uwa3-s\.optemp\packages\opbuild.scripts.1.80.0-alpha-20190903070236-g5466eb1\tools\opbuild\docset.prebuild.ps1 failed to execute`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C4%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909040309213774-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zm5f0cUa5E14fgR37NwfzeKL4%2FTy7Lv4Q3Cn2iX4Pj8%3D&st=2019-09-04T03%3A14%3A58Z&se=2019-10-05T03%3A19%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[240eb7b](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/240eb7bffe5dd940623510fb8e7f6d0beb9031eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-ffb96774)
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docfx.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/docfx.json) | :white_check_mark:Succeeded | |

<a id="ffb96774"></a>
###
 - **[Warning]** `````Cannot find docset information for repository: 6333a4b0-869f-2b4a-a954-6d5820d2e35e and docset name: azuredotnet. Please make sure the docset is correctly provisioned`````
 - **[Warning]** `````No provisioned docset found in repository 6333a4b0-869f-2b4a-a954-6d5820d2e35e. Please provision or restore the docsets if you want to build them`````
 - **[Warning]** `````No document is published`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C4%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909040730569844-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XQQYZd5FbM3P5wz%2BaJ9xziEPYeSG%2Fj9QFxcc2dOoWN4%3D&st=2019-09-04T07%3A34%3A56Z&se=2019-10-05T07%3A39%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[240eb7b](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/240eb7bffe5dd940623510fb8e7f6d0beb9031eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-6a77cac2)
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docfx.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/docfx.json) | :white_check_mark:Succeeded | |

<a id="6a77cac2"></a>
###
 - **[Warning]** `````Cannot find docset information for repository: 6333a4b0-869f-2b4a-a954-6d5820d2e35e and docset name: azuredotnet. Please make sure the docset is correctly provisioned`````
 - **[Warning]** `````No provisioned docset found in repository 6333a4b0-869f-2b4a-a954-6d5820d2e35e. Please provision or restore the docsets if you want to build them`````
 - **[Warning]** `````No document is published`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C4%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909040748208933-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fQRuWY%2FkAH07dWj5iDwtAEjdf6nlBY%2FcM2pz8pbzHKU%3D&st=2019-09-04T07%3A51%3A43Z&se=2019-10-05T07%3A56%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
