### PR TITLE
Resolve syncing conflicts from master-sync-work to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from master-sync-work to master.

### CODE REVIEW

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\guxx-s, target branch: master, target branch commit: a5e2f3ad19767e316504f5e10945a931dfb225e4, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C26%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201709260418262444-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7wRBEK6prKeRGvX5Pc87JiJE3RhYOctqjM77VpRI5H8%3D&st=2017-09-26T04%3A18%3A14Z&se=2017-09-27T04%3A28%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\j42o-s, target branch: master, target branch commit: a5e2f3ad19767e316504f5e10945a931dfb225e4, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C26%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201709260419298003-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hyCECelLgcT6ajko2EZjf3OhkvWsRf1rNAOSaiAGnYI%3D&st=2017-09-26T04%3A23%3A34Z&se=2017-09-27T04%3A33%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Invalid syntax in .openpublishing.publish.config.json. Please validate your syntax with a JSON validator like http://jsonlint.com/ and update the json file in the repo with a correct syntax

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C26%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201709260904128424-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=d09BRFcvzfgRV26OnPLy9uHj3nRMCjo6JF7VpZUHdI8%3D&st=2017-09-26T09%3A04%3A16Z&se=2017-09-27T09%3A14%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Invalid syntax in .openpublishing.publish.config.json. Please validate your syntax with a JSON validator like http://jsonlint.com/ and update the json file in the repo with a correct syntax

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C27%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201709270259198611-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XkH8DbVtIPzcSqNWGEYVjkfME8eHaQEHqye%2FbHGOQGQ%3D&st=2017-09-27T02%3A58%3A44Z&se=2017-10-28T03%3A03%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Invalid syntax in .openpublishing.publish.config.json. Please validate your syntax with a JSON validator like http://jsonlint.com/ and update the json file in the repo with a correct syntax

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C27%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201709270311024089-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GpQmSnaMBPudwydCdx8aDOPpx%2BppzoaijstKSRgEsMM%3D&st=2017-09-27T03%3A10%3A22Z&se=2017-10-28T03%3A15%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Invalid syntax in .openpublishing.publish.config.json. Please validate your syntax with a JSON validator like http://jsonlint.com/ and update the json file in the repo with a correct syntax

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C27%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201709270325043139-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=X%2BDGFJGZF63gVspLZSTT%2FtwVbWrrhJdvFWwPnBgrr2A%3D&st=2017-09-27T03%3A24%3A21Z&se=2017-10-28T03%3A29%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Invalid syntax in .openpublishing.publish.config.json. Please validate your syntax with a JSON validator like http://jsonlint.com/ and update the json file in the repo with a correct syntax

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C27%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201709270455241468-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wfESSzzTmBqvYzDR%2F9HsyHCK%2BkqApkePbaDT%2BGhp%2Bo4%3D&st=2017-09-27T05%3A05%3A35Z&se=2017-10-28T05%3A10%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C27%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201709270606037989-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zCgnIfKvJKNC3UKxwVrb%2BzJFhA17GLeo6N2Rabs3K6g%3D&st=2017-09-27T06%3A47%3A57Z&se=2017-10-28T06%3A52%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
