### PR TITLE
Resolve syncing conflicts from master-sync-work to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from master-sync-work to master.

### CODE REVIEW

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\v0o2-s, target branch: master, target branch commit: f6022cf1023d8614750575ca6fddff7dd0a48385, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C24%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707240108508113-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\ksjb-s, target branch: master, target branch commit: f6022cf1023d8614750575ca6fddff7dd0a48385, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C24%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707241857151942-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\2mv4-s, target branch: master, target branch commit: f6022cf1023d8614750575ca6fddff7dd0a48385, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C24%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707241858183617-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\vrh4-s, target branch: master, target branch commit: f6022cf1023d8614750575ca6fddff7dd0a48385, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C24%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707242124488515-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/.openpublishing.publish.config.json) | :x:Error | | [Details](#user-content-.openpublishing.publish.config.json)

<a name=".openpublishing.publish.config.json"></a>
### [.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/.openpublishing.publish.config.json)
 - **[Error]** Moniker azurebatch-7.0.1 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azurecosmosdbcfp-1.0.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuredevicesclient-1.3.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtdatalakeanalytics-2.2.1-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtdatalakeanalytics-3.0.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtdatalakestore-2.1.3-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtdatalakestore-2.2.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtresourcemanager-1.6.0-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtservicebus-1.0.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremobileserverentity-2.0.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azureservicebus-0.0.6-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azureservicebus-4.1.1 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmttrafficmanager-2.3.0-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker enterpriselibtfh-6.0.1304.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C25%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707250344008848-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Micosnow** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\nmku-o-bf75f6bf\raw-\pelq2dgy.zwu\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\nmku-o-bf75f6bf\raw-\pelq2dgy.zwu\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C25%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707250505494698-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Micosnow** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\ojih-s, target branch: master, target branch commit: f6022cf1023d8614750575ca6fddff7dd0a48385, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C25%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707251734421114-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\uzo3-s, target branch: master, target branch commit: f6022cf1023d8614750575ca6fddff7dd0a48385, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C25%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707251737481619-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot merge commit 2e1e8de23652df95c978d6b91e2f87774984442b in branch master-sync-work of repository https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet into branch master (commit f6022cf1023d8614750575ca6fddff7dd0a48385)

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C25%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707251949477071-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Micosnow** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\gouv-o-a87f017e\raw-\nratd4ub.rd1\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\gouv-o-a87f017e\raw-\nratd4ub.rd1\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C26%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707260120007990-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[api/overview/azure/index.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\hna1-o-234ee3d4\raw-\oiuimbdu.wz5\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 
 - **Line 124**: **[Error]** Pull content in folder W:\hna1-s\_themes failed. Error: remote: Repository not found. fatal: repository &#39;https://username:6809232e09e0c24d8bfa9b915ced8b053e47020d@github.com/Microsoft/templates.docs.msft/&#39; not found 

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\hna1-o-234ee3d4\raw-\oiuimbdu.wz5\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C26%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707260632571663-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\qtke-o-3c4ba11c\raw-\txy4syxm.hkh\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\qtke-o-3c4ba11c\raw-\txy4syxm.hkh\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C27%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707270048232621-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\dz2e-o-a12d5ff7\raw-\qgssutrw.ux4\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\dz2e-o-a12d5ff7\raw-\qgssutrw.ux4\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C7%5C27%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201707270545344405-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
