### PR TITLE
Resolve syncing conflicts from master-sync-work to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from master-sync-work to master.

### CODE REVIEW

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\h0ih-s, target branch: master, target branch commit: 9e399e812cdfe1a3f932218c5bae1f64e1ee7ae7, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C13%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806131732312613-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QuQMFXdKsNGdDojw4YdM0rf2%2B2J%2FGFO%2FL9xjtAhw%2Fp8%3D&st=2018-06-13T17%3A35%3A33Z&se=2018-07-14T17%3A40%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\ho2x-s, target branch: master, target branch commit: 9e399e812cdfe1a3f932218c5bae1f64e1ee7ae7, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C13%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806131835353919-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=m%2Fgw8U4WasHwopuLaD9nTsiRfhWCI1%2BSp4z7plEZjGc%3D&st=2018-06-13T18%3A37%3A58Z&se=2018-07-14T18%3A42%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\p0ym-s, target branch: master, target branch commit: 9e399e812cdfe1a3f932218c5bae1f64e1ee7ae7, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C13%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806132114262636-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8SQ2Kvq%2BKnNyvU2Y1tyEgLI66cVNgquNFRprwjjPmsc%3D&st=2018-06-13T21%3A17%3A20Z&se=2018-07-14T21%3A22%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[_zip/msdn.4.5.2.zip](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/_zip/msdn.4.5.2.zip) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/azure-dotnet.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/FrameworksIndex/azure-dotnet.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/CloudTableClient.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.CosmosDB.Table/CloudTableClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IBlank.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IBlank.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IDefinition.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IDefinition.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithAgentPool.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithAgentPool.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithCreate.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithCreate.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithDiagnostics.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithDiagnostics.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithGroup.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithGroup.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithLinux.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithLinux.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithLinuxRootUsername.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithLinuxRootUsername.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithLinuxSshKey.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithLinuxSshKey.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterDnsPrefix.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterDnsPrefix.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterNodeCount.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterNodeCount.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterOSDiskSize.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterOSDiskSize.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterStorageProfile.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterStorageProfile.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterVMSize.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterVMSize.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithOrchestrator.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithOrchestrator.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithServicePrincipalProfile.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithServicePrincipalProfile.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithSubnet.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithSubnet.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Update/IUpdate.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Update/IUpdate.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Update/IWithDiagnostics.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Update/IWithDiagnostics.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Update/IWithUpdateAgentPoolCount.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Update/IWithUpdateAgentPoolCount.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IBlank`1.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IBlank%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IDefinition`1.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IDefinition%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithAttach`1.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithAttach%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithLeafDomainLabel`1.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithLeafDomainLabel%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithOSDiskSize`1.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithOSDiskSize%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithOSType`1.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithOSType%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithPorts`1.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithPorts%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithStorageProfile`1.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithStorageProfile%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithSubnet`1.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithSubnet%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithVMSize`1.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithVMSize%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IBlank.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IBlank.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IDefinition.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IDefinition.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithAgentPool.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithAgentPool.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithCreate.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithCreate.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithDnsPrefix.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithDnsPrefix.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithGroup.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithGroup.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithKeyVaultSecret.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithKeyVaultSecret.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithLinuxRootUsername.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithLinuxRootUsername.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithLinuxSshKey.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithLinuxSshKey.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithServicePrincipalClientId.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithServicePrincipalClientId.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithServicePrincipalProfile.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithServicePrincipalProfile.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithVersion.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithVersion.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Update/IUpdate.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Update/IUpdate.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Update/IWithUpdateAgentPoolCount.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Update/IWithUpdateAgentPoolCount.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesClusterAgentPool.Definition/IBlank`1.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesClusterAgentPool.Definition/IBlank%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesClusterAgentPool.Definition/IDefinition`1.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesClusterAgentPool.Definition/IDefinition%601.xml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C14%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201806140124148025-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ieIdMaZIXHlBkz4%2BBl1fQsTr8Vw7MkTeoshBW1%2BxvEE%3D&st=2018-06-14T01%3A42%3A13Z&se=2018-07-15T01%3A47%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
