### PR TITLE
Resolve syncing conflicts from live-sync-work to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from live-sync-work to live.

### CODE REVIEW

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[ec7274d](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/ec7274d59322b7c6503ec102bf8b9670887a80bb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-38fa2b73)

<a id="38fa2b73"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\dv4x-s, target branch: HEAD, target branch commit: 04c085e79d324602feccc0617fba74219c80ff12, source commit: ec7274d59322b7c6503ec102bf8b9670887a80bb.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C3%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909032315551676-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aqHGehm%2BeFqT2l9Be3JxbdT0warWgh1CoNQjIVNImO4%3D&st=2019-09-03T23%3A19%3A44Z&se=2019-10-04T23%3A24%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[ec7274d](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/ec7274d59322b7c6503ec102bf8b9670887a80bb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a5eb6292)

<a id="a5eb6292"></a>
###
 - **[Error]** `````Cannot merge commit ec7274d59322b7c6503ec102bf8b9670887a80bb in branch live-sync-work of repository https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet into branch live (commit 04c085e79d324602feccc0617fba74219c80ff12). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C4%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909040244367970-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=faTB0lh%2BPkXovJ6Nc9fDP7SNJYM3MPdkf3FN2LHHycM%3D&st=2019-09-04T02%3A39%3A55Z&se=2019-10-05T02%3A44%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[5df32a1](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/5df32a1099b4ea9a9985c5223e898018f8c3ec25)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a7903c00)

<a id="a7903c00"></a>
###
 - **[Error]** `````Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C4%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909040244589699-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C9V9HRgQBGFXTbwrgnJmhlL0ooiT3%2FnWlTxe3jgguaQ%3D&st=2019-09-04T02%3A48%3A41Z&se=2019-10-05T02%3A53%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[5df32a1](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/5df32a1099b4ea9a9985c5223e898018f8c3ec25)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-33ad0fea)

<a id="33ad0fea"></a>
###
 - **[Error]** `````Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C4%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909040309069408-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SsuJVYq9AjOCIGiBn%2FgxDN2r%2B945sQOaZvq7hjW7iMk%3D&st=2019-09-04T03%3A13%3A11Z&se=2019-10-05T03%3A18%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[5df32a1](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/5df32a1099b4ea9a9985c5223e898018f8c3ec25)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e75ce731)

<a id="e75ce731"></a>
###
 - **[Error]** `````Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C4%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909040732278201-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TvHVRr9ToNZ6r9oIBMGIfUTgWmHTIvb%2BziR1SePZ%2FgU%3D&st=2019-09-04T07%3A36%3A02Z&se=2019-10-05T07%3A41%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[6f80530](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/6f80530d9dc3ca23bb0894e5d47cd1bdfd53a662)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5c0c9d4a)
[]() | :x:Error | | [Details](#user-content-5c0c9d4a)

<a id="5c0c9d4a"></a>
###
 - **[Error]** `````Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot`````
 - **[Warning]** `````Cannot find docset information for repository: 6333a4b0-869f-2b4a-a954-6d5820d2e35e and docset name: azuredotnet. Please make sure the docset is correctly provisioned`````
 - **[Warning]** `````No provisioned docset found in repository 6333a4b0-869f-2b4a-a954-6d5820d2e35e. Please provision or restore the docsets if you want to build them`````

<a id="5c0c9d4a"></a>
###
 - **[Error]** `````Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot`````
 - **[Warning]** `````Cannot find docset information for repository: 6333a4b0-869f-2b4a-a954-6d5820d2e35e and docset name: azuredotnet. Please make sure the docset is correctly provisioned`````
 - **[Warning]** `````No provisioned docset found in repository 6333a4b0-869f-2b4a-a954-6d5820d2e35e. Please provision or restore the docsets if you want to build them`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C4%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909040749266672-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SPAwW%2FiXEH6WLzAFPD0ot60n55awFVe%2BaxDsLVozBo4%3D&st=2019-09-04T07%3A53%3A20Z&se=2019-10-05T07%3A58%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
