### PR TITLE
Resolve syncing conflicts from live-sync-work to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from live-sync-work to live.

### CODE REVIEW

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\hnfx-s, target branch: live, target branch commit: afec1d8f8e3f0ac0b06742e64da71a1044ea5922, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C26%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201709260712050774-19%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5auSvU6vJTgRvcLZ3%2F0ky8LnU9f6Y28rhlEBehYTBEg%3D&st=2017-09-26T07%3A17%3A44Z&se=2017-09-27T07%3A27%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/live-sync-work/.openpublishing.publish.config.json) | :x:Error | | [Details](#user-content-.openpublishing.publish.config.json)

<a name=".openpublishing.publish.config.json"></a>
### [.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/live-sync-work/.openpublishing.publish.config.json)
 - **[Error]** Moniker azurebatch-7.1.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azurebatchfilestaging-7.0.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azurecosmosdbcfp-1.1.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azurecosmosdbcfp-1.1.1 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azurecosmosdbcore-1.5.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuredocumentdb-1.16.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuredocumentdb-1.17.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuregraphs-0.2.4-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtauthorization-2.0.1 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtbatch-5.1.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtbilling-2.0.0-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtcompute-16.2.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtdatalakeanalytics-3.1.0-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtdatalakeanalytics-3.1.1-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtdatalakestore-2.3.0-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtdns-1.9.0-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmteventhub-2.0.1 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtiothub-1.1.2 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtkeyvault-2.3.0-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtnetwork-14.0.0-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtnotificationhubs-2.3.1-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtrecoveryservices-4.2.0-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtrecoveryservicesbackup-2.1.0-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtsql-1.6.0-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtstorage-7.0.0-preview doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremgmtstreamanalytics-2.0.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremobileserverauth-2.0.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremobileservercrossdomain-2.0.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremobileserverhome-2.0.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremobileservernotifications-2.0.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azuremobileservertables-2.0.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azureservicebuseps-3.1.2 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker azurestorage-8.4.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker identitymodelclientsad-3.16.0 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker powerbiapi-2.0.3 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker servicefabric-5.7.198 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker servicefabric-aspnetcore-kestrel-2.7.198 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker servicefabric-aspnetcore-weblistener-2.7.198 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker servicefabric-fabrictransportint-2.7.198 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker servicefabricactors-2.7.198 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker servicefabricactorswcf-2.7.198 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker servicefabricdata-2.7.198 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker servicefabricsvcs-2.7.198 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker servicefabricsvcsremoting-2.7.198 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.
 - **[Error]** Moniker servicefabricsvcswcf-2.7.198 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C26%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201709260905370627-19%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qDSDmPCUcVJNAzOmAphk%2FfQ6QutnxhqHm0iLLcR1IlE%3D&st=2017-09-26T09%3A07%3A40Z&se=2017-09-27T09%3A17%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/live-sync-work/.openpublishing.publish.config.json) | :x:Error | | [Details](#user-content-.openpublishing.publish.config.json)

<a name=".openpublishing.publish.config.json"></a>
### [.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/live-sync-work/.openpublishing.publish.config.json)
 - **[Error]** Moniker servicefabricsvcswcf-2.7.198 doesn&#39;t exist in moniker service. Depot e2eppe-azuredotnet content won&#39;t be published.

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C27%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201709270256576733-19%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2zC0Jj4r9YtKYJlLIfrBLdEXri1wd8RGwRN97t%2FJIOw%3D&st=2017-09-27T02%3A59%3A34Z&se=2017-10-28T03%3A04%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[index.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/live-sync-work/index.xml) | :warning:Warning | | [Details](#user-content-index.xml)
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/live-sync-work/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

<a name="index.xml"></a>
### [index.xml](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/live-sync-work/index.xml)
 - **[Warning]** ExtensionMethod M:System.Web.Http.TraceWriterExtensions.Warn(System.Web.Http.Tracing.ITraceWriter,System.String,System.Net.Http.HttpRequestMessage,System.String) not found in its type System.Web.Http.TraceWriterExtensions
 - **[Warning]** ExtensionMethod M:System.Web.Http.TraceWriterExtensions.Trace(System.Web.Http.Tracing.ITraceWriter,System.Web.Http.Tracing.TraceLevel,System.String,System.Exception,System.Net.Http.HttpRequestMessage,System.String) not found in its type System.Web.Http.TraceWriterExtensions
 - **[Warning]** ExtensionMethod M:System.Web.Http.TraceWriterExtensions.Info(System.Web.Http.Tracing.ITraceWriter,System.String,System.Net.Http.HttpRequestMessage,System.String) not found in its type System.Web.Http.TraceWriterExtensions
 - **[Warning]** ExtensionMethod M:System.Web.Http.TraceWriterExtensions.Error(System.Web.Http.Tracing.ITraceWriter,System.String,System.Net.Http.HttpRequestMessage,System.String) not found in its type System.Web.Http.TraceWriterExtensions
 - **[Warning]** ExtensionMethod M:System.Web.Http.TraceWriterExtensions.Error(System.Web.Http.Tracing.ITraceWriter,System.String,System.Exception,System.Net.Http.HttpRequestMessage,System.String) not found in its type System.Web.Http.TraceWriterExtensions
 - **[Warning]** ExtensionMethod M:System.Web.Http.TraceWriterExtensions.Error(System.Web.Http.Tracing.ITraceWriter,System.Exception,System.Net.Http.HttpRequestMessage,System.String) not found in its type System.Web.Http.TraceWriterExtensions
 - **[Warning]** ExtensionMethod M:System.Web.Http.TraceWriterExtensions.Debug(System.Web.Http.Tracing.ITraceWriter,System.String,System.Net.Http.HttpRequestMessage,System.String) not found in its type System.Web.Http.TraceWriterExtensions
 - **[Warning]** ExtensionMethod M:System.Web.Http.TableHttpConfigurationExtensions.SetTableControllerConfigProvider(System.Web.Http.HttpConfiguration,Microsoft.Azure.Mobile.Server.Tables.ITableControllerConfigProvider) not found in its type System.Web.Http.TableHttpConfigurationExtensions
 - **[Warning]** ExtensionMethod M:System.Web.Http.TableHttpConfigurationExtensions.GetTableControllerNames(System.Web.Http.HttpConfiguration) not found in its type System.Web.Http.TableHttpConfigurationExtensions
 - **[Warning]** ExtensionMethod M:System.Web.Http.TableHttpConfigurationExtensions.GetTableControllerConfigProvider(System.Web.Http.HttpConfiguration) not found in its type System.Web.Http.TableHttpConfigurationExtensions
 - **[Warning]** ExtensionMethod M:System.Web.Http.AuthenticationHttpConfigurationExtensions.SetAppServiceTokenHandler(System.Web.Http.HttpConfiguration,Microsoft.Azure.Mobile.Server.Authentication.IAppServiceTokenHandler) not found in its type System.Web.Http.AuthenticationHttpConfigurationExtensions
 - **[Warning]** ExtensionMethod M:System.Web.Http.AuthenticationHttpConfigurationExtensions.GetAppServiceTokenHandler(System.Web.Http.HttpConfiguration) not found in its type System.Web.Http.AuthenticationHttpConfigurationExtensions
 - **[Warning]** ExtensionMethod M:System.Security.Principal.IPrincipalExtensions.GetAppServiceIdentityAsync``1(System.Security.Principal.IPrincipal,System.Net.Http.HttpRequestMessage,System.Net.Http.HttpClient) not found in its type System.Security.Principal.IPrincipalExtensions
 - **[Warning]** ExtensionMethod M:System.Security.Principal.IPrincipalExtensions.GetAppServiceIdentityAsync``1(System.Security.Principal.IPrincipal,System.Net.Http.HttpRequestMessage) not found in its type System.Security.Principal.IPrincipalExtensions
 - **[Warning]** ExtensionMethod M:System.Net.Http.TableHttpRequestMessageExtensions.SetSelectedProperties(System.Net.Http.HttpRequestMessage,System.Type,System.Collections.Generic.IDictionary{System.String,System.String},System.Boolean@) not found in its type System.Net.Http.TableHttpRequestMessageExtensions
 - **[Warning]** ExtensionMethod M:System.Net.Http.TableHttpRequestMessageExtensions.SetSelectedProperties(System.Net.Http.HttpRequestMessage,System.Type,System.Boolean@) not found in its type System.Net.Http.TableHttpRequestMessageExtensions
 - **[Warning]** ExtensionMethod M:System.Net.Http.TableHttpRequestMessageExtensions.GetVersionFromIfMatch(System.Net.Http.HttpRequestMessage) not found in its type System.Net.Http.TableHttpRequestMessageExtensions
 - **[Warning]** ExtensionMethod M:System.Net.Http.TableHttpRequestMessageExtensions.AreDeletedRowsRequested(System.Net.Http.HttpRequestMessage) not found in its type System.Net.Http.TableHttpRequestMessageExtensions
 - **[Warning]** ExtensionMethod M:System.Net.Http.HttpRequestMessageExtensions.IsIfNoneMatch(System.Net.Http.HttpRequestMessage,System.Net.Http.Headers.EntityTagHeaderValue) not found in its type System.Net.Http.HttpRequestMessageExtensions
 - **[Warning]** ExtensionMethod M:System.Net.Http.HttpRequestMessageExtensions.GetHeaderOrDefault(System.Net.Http.HttpRequestMessage,System.String) not found in its type System.Net.Http.HttpRequestMessageExtensions
 - **[Warning]** ExtensionMethod M:System.Net.Http.HttpRequestMessageExtensions.CreateUnauthorizedResponse(System.Net.Http.HttpRequestMessage,System.String,System.Object[]) not found in its type System.Net.Http.HttpRequestMessageExtensions
 - **[Warning]** ExtensionMethod M:System.Net.Http.HttpRequestMessageExtensions.CreateUnauthorizedResponse(System.Net.Http.HttpRequestMessage) not found in its type System.Net.Http.HttpRequestMessageExtensions
 - **[Warning]** ExtensionMethod M:System.Net.Http.HttpRequestMessageExtensions.CreateNotFoundResponse(System.Net.Http.HttpRequestMessage,System.String,System.Object[]) not found in its type System.Net.Http.HttpRequestMessageExtensions
 - **[Warning]** ExtensionMethod M:System.Net.Http.HttpRequestMessageExtensions.CreateNotFoundResponse(System.Net.Http.HttpRequestMessage) not found in its type System.Net.Http.HttpRequestMessageExtensions
 - **[Warning]** ExtensionMethod M:System.Net.Http.HttpRequestMessageExtensions.CreateBadRequestResponse(System.Net.Http.HttpRequestMessage,System.String,System.Object[]) not found in its type System.Net.Http.HttpRequestMessageExtensions
 - **[Warning]** ExtensionMethod M:System.Net.Http.HttpRequestMessageExtensions.CreateBadRequestResponse(System.Net.Http.HttpRequestMessage) not found in its type System.Net.Http.HttpRequestMessageExtensions
 - **[Warning]** ExtensionMethod M:Mono.CSharp.TypeExtensions.GetNamespace(System.Type) not found in its type Mono.CSharp.TypeExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.Azure.Mobile.Server.Config.TableMobileAppOptionsExtensions.WithTableControllerConfigProvider(Microsoft.Azure.Mobile.Server.Config.MobileAppConfiguration,Microsoft.Azure.Mobile.Server.Tables.ITableControllerConfigProvider) not found in its type Microsoft.Azure.Mobile.Server.Config.TableMobileAppOptionsExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.Azure.Mobile.Server.Config.TableMobileAppOptionsExtensions.AddTables(Microsoft.Azure.Mobile.Server.Config.MobileAppConfiguration,Microsoft.Azure.Mobile.Server.Tables.Config.MobileAppTableConfiguration) not found in its type Microsoft.Azure.Mobile.Server.Config.TableMobileAppOptionsExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.Azure.Mobile.Server.Config.TableMobileAppOptionsExtensions.AddTables(Microsoft.Azure.Mobile.Server.Config.MobileAppConfiguration) not found in its type Microsoft.Azure.Mobile.Server.Config.TableMobileAppOptionsExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.ApplicationInsights.TelemetryClientExtensions.StopOperation``1(Microsoft.ApplicationInsights.TelemetryClient,Microsoft.ApplicationInsights.Extensibility.IOperationHolder{``0}) not found in its type Microsoft.ApplicationInsights.TelemetryClientExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation``1(Microsoft.ApplicationInsights.TelemetryClient,System.String,System.String,System.String) not found in its type Microsoft.ApplicationInsights.TelemetryClientExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation``1(Microsoft.ApplicationInsights.TelemetryClient,System.String) not found in its type Microsoft.ApplicationInsights.TelemetryClientExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation``1(Microsoft.ApplicationInsights.TelemetryClient,``0) not found in its type Microsoft.ApplicationInsights.TelemetryClientExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.ApplicationInsights.OperationTelemetryExtensions.Stop(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry,System.Int64) not found in its type Microsoft.ApplicationInsights.OperationTelemetryExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.ApplicationInsights.OperationTelemetryExtensions.Stop(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry) not found in its type Microsoft.ApplicationInsights.OperationTelemetryExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.ApplicationInsights.OperationTelemetryExtensions.Start(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry,System.Int64) not found in its type Microsoft.ApplicationInsights.OperationTelemetryExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.ApplicationInsights.OperationTelemetryExtensions.Start(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry) not found in its type Microsoft.ApplicationInsights.OperationTelemetryExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.ApplicationInsights.OperationTelemetryExtensions.GenerateOperationId(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry) not found in its type Microsoft.ApplicationInsights.OperationTelemetryExtensions
 - **[Warning]** ExtensionMethod M:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions.ToInvariantString(System.Exception) not found in its type Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions
 - **[Warning]** ExtensionMethod M:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions.GetInternalContext(Microsoft.ApplicationInsights.DataContracts.TelemetryContext) not found in its type Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C27%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201709270311423738-19%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YTNcH%2BlbZOruLIQiOKQB8C8l8fHPPgxyktFf2ojQJ1w%3D&st=2017-09-27T03%3A50%3A09Z&se=2017-10-28T03%3A55%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
