### PR TITLE
Create TestingPullRequest.md

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by luyajun0205** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C19%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801190726493570-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ykNuDduXvbtFZ%2BuHmLiXmrWEQTNgTn9ZFtfEjVTPbt4%3D&st=2018-01-19T08%3A18%3A03Z&se=2018-02-19T08%3A23%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C19%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801190733057034-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=D8M6ehYLAFip6r97OYyFvStUU8FcNPrhWFgWlnJ4vgM%3D&st=2018-01-19T09%3A18%3A29Z&se=2018-02-19T09%3A23%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C22%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801220214408574-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kC9OiXmovQUkuy0fh5o8waOeie8lCBqrKGfgfpWwF0Y%3D&st=2018-01-22T03%3A06%3A11Z&se=2018-02-22T03%3A11%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C22%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801220443042049-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=R12y%2BH7cJ7HAN1%2Bqoms2ZUfVxYwMnZR%2FfizNvU9yDYM%3D&st=2018-01-22T05%3A36%3A14Z&se=2018-02-22T05%3A41%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C22%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801220710104133-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tjPyuLcyaNMWKXDR6hFhWxPilywD7zRmDedW2NXJfvY%3D&st=2018-01-22T07%3A21%3A23Z&se=2018-02-22T07%3A26%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C22%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801220841285044-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=poWyEgRAlqbqY3hpZOQ0oKM1xHbRg0HUlt0wxPV4QHQ%3D&st=2018-01-22T08%3A52%3A37Z&se=2018-02-22T08%3A57%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C23%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801230834252862-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Z0zTDsHHXWrlNz5gByPq%2F0k20f4e%2Fnreiq8Dg8OSBGM%3D&st=2018-01-23T08%3A46%3A39Z&se=2018-02-23T08%3A51%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C23%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801231000061563-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zvcN2bvpfbfSJNhnVHlLhcQS3Hp671nc6IloeTgohIA%3D&st=2018-01-23T10%3A08%3A09Z&se=2018-02-23T10%3A13%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C24%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801240134182401-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jAylpB%2BrBdEsDezQIin1YxYyIUiMtjsqlqVZwn%2Fj4n0%3D&st=2018-01-24T02%3A36%3A14Z&se=2018-02-24T02%3A41%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C24%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801240351271785-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FVH%2F40cIMTCTR%2BkqMWa4yQm8Jp9HSpKGXZElI%2Fjr6tw%3D&st=2018-01-24T04%3A01%3A01Z&se=2018-02-24T04%3A06%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C24%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801240609568391-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8T2C32AeamsPN56ONVFNq1xh4U4J5QqSmcsy2i%2BglYA%3D&st=2018-01-24T06%3A19%3A05Z&se=2018-02-24T06%3A24%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C24%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801240859121653-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zwMQ0zxbhn8uxbBicwQSYKUdCluBkE1m3Ukn1hOQSOo%3D&st=2018-01-24T09%3A08%3A05Z&se=2018-02-24T09%3A13%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C24%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801241021275379-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2t33Oh2gYxAcrMJG4Ypx7gNI4wLF2v00%2FrB9opBUBYA%3D&st=2018-01-24T10%3A30%3A08Z&se=2018-02-24T10%3A35%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C25%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801250155043998-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dBJlbLWGBnE59D3SXPLPhA4ucC4IUugTnL5bfOT3KdU%3D&st=2018-01-25T02%3A04%3A30Z&se=2018-02-25T02%3A09%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C25%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801250323354141-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NpfFiOfi5VgEzl4QBhC2wK4cLW5Sub9kpWc9AiqUtrE%3D&st=2018-01-25T03%3A32%3A28Z&se=2018-02-25T03%3A37%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C25%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801250628000284-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OGMOZnqw4%2BG3eRD36lFh2k03bq3u91BXtJxA6CkPomA%3D&st=2018-01-25T06%3A37%3A24Z&se=2018-02-25T06%3A42%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azuredotnet/api/overview/azure/testingpullrequest?branch=pr-en-us-26) | [Details](#user-content-api%2Foverview%2Fazure%2FTestingPullRequest.md)

<a name="api%2Foverview%2Fazure%2FTestingPullRequest.md"></a>
### [api/overview/azure/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/blob/prtest/api/overview/azure/TestingPullRequest.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 8**: **[Warning]** Invalid file link:(~/api/overview/nonexisted1.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/api/overview/nonexisted2.md).
 - **Line 10**: **[Warning]** Invalid file link:(~/api/overview/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C25%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201801250750300515-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8143tZ%2B5PqvpK1ZnrUrpTl5pEhDGYKjUYpHywgzCyNA%3D&st=2018-01-25T07%3A58%3A57Z&se=2018-02-25T08%3A03%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
