### PR TITLE
Resolve syncing conflicts from repo_sync_novalidation_live_branch to live-nometavalidation

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from repo_sync_novalidation_live_branch to live-nometavalidation.

### CODE REVIEW

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[117d8fb](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/117d8fbb59c57cea5ed44ea0f01d6a4356733ce8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6a4752eb)

<a id="6a4752eb"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\xbzq-s, target branch: HEAD, target branch commit: 74c53b0ba7a0bb3d31c14db7f16785ba33b32a4b, source commit: 117d8fbb59c57cea5ed44ea0f01d6a4356733ce8.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C4%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909040839119822-62%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7CVH%2BJ8ul9rfXyC6ZO9u9IIv3oJHC8vgmIrgC7TpjHs%3D&st=2019-09-04T08%3A45%3A06Z&se=2019-10-05T08%3A50%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[f05406b](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/f05406b7fbd000df6ee042a16c9969c08b025e06)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-babe3ee5)

<a id="babe3ee5"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\nsux-s, target branch: HEAD, target branch commit: 74c53b0ba7a0bb3d31c14db7f16785ba33b32a4b, source commit: f05406b7fbd000df6ee042a16c9969c08b025e06.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C5%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909050109298754-62%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CoEvOjwVnHJs75i39WxGaJxdyOQ0GCMGITfvqIyvaJE%3D&st=2019-09-05T01%3A18%3A05Z&se=2019-10-06T01%3A23%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[ba616db](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/ba616db4c2f0b997001dfc187c0e8df107ad2993)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-adfc61e7)

<a id="adfc61e7"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\550o-s, target branch: HEAD, target branch commit: 74c53b0ba7a0bb3d31c14db7f16785ba33b32a4b, source commit: ba616db4c2f0b997001dfc187c0e8df107ad2993.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C5%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909050708589513-62%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oMTl%2BKTcTAJBqnzi77lluP%2BLLE7CgUgs9ZBdMR2o0yw%3D&st=2019-09-05T07%3A12%3A48Z&se=2019-10-06T07%3A17%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[3ba2231](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/3ba22316123f5f8b8ee440b96403e58b8780a849)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-492dab05)

<a id="492dab05"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\f0q1-s, target branch: HEAD, target branch commit: 74c53b0ba7a0bb3d31c14db7f16785ba33b32a4b, source commit: 3ba22316123f5f8b8ee440b96403e58b8780a849.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C5%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909051236317567-62%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C%2B3BnrHwyzhiGT7%2FLNIzTpsdHDDgYUmaW8baH%2B%2BNQMo%3D&st=2019-09-05T12%3A46%3A36Z&se=2019-10-06T12%3A51%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[bea055b](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/bea055b9445fa4485126d6006102a7f4f82acd33)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-db16c998)

<a id="db16c998"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\z5bx-s, target branch: HEAD, target branch commit: 74c53b0ba7a0bb3d31c14db7f16785ba33b32a4b, source commit: bea055b9445fa4485126d6006102a7f4f82acd33.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C5%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909051245147383-62%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nYnr0ePNL4KlyAMOLBO4TrUysHybXtww%2BWNYgKMNWd0%3D&st=2019-09-05T12%3A58%3A40Z&se=2019-10-06T13%3A03%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[6a83cc5](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/6a83cc5a71cd73d6d4743a6cdf5174e4590ae9a1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2644ec58)

<a id="2644ec58"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\j1vl-s, target branch: HEAD, target branch commit: 74c53b0ba7a0bb3d31c14db7f16785ba33b32a4b, source commit: 6a83cc5a71cd73d6d4743a6cdf5174e4590ae9a1.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C19%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909192251061802-62%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VveTfHKKUfvxN6Y%2FGipuzn66cXiwaztDbH22WXvIvj8%3D&st=2019-09-19T22%3A55%3A33Z&se=2019-10-20T23%3A00%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[689aade](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/689aadedd8f79a28a3ab5674cd31a1eac07483ce)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-84ebe8e2)

<a id="84ebe8e2"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\pvn2-s, target branch: HEAD, target branch commit: 74c53b0ba7a0bb3d31c14db7f16785ba33b32a4b, source commit: 689aadedd8f79a28a3ab5674cd31a1eac07483ce.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C24%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201909242248334219-62%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1D4mUsyYBAAyvOnJ%2BUuvBvE0Qm6Sz5UXbc9SWz3CXpE%3D&st=2019-09-24T22%3A52%3A45Z&se=2019-10-25T22%3A57%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[b78fe5e](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/b78fe5ea272d466c99f438d4f807171d2f3b9a28)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-303856b9)

<a id="303856b9"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\c4mv-s, target branch: HEAD, target branch commit: 74c53b0ba7a0bb3d31c14db7f16785ba33b32a4b, source commit: b78fe5ea272d466c99f438d4f807171d2f3b9a28.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C2%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201910022110327161-62%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NHVMnHMrHtAcUsfdIH53BivpL3ts1uvP1b5vB7YzZTg%3D&st=2019-10-02T21%3A15%3A25Z&se=2019-11-02T21%3A20%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[2b26ee2](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/2b26ee26dc19ae02b4eeb35fd45a573aa6c5e834)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[2b26ee2](https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet/commits/2b26ee26dc19ae02b4eeb35fd45a573aa6c5e834)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5531cf69)

<a id="5531cf69"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-sdk-dotnet, working directory: W:\hoev-s, target branch: HEAD, target branch commit: 74c53b0ba7a0bb3d31c14db7f16785ba33b32a4b, source commit: 2b26ee26dc19ae02b4eeb35fd45a573aa6c5e834.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C9%5C6333a4b0-869f-2b4a-a954-6d5820d2e35e%5CPullRequest%5C201910091925060534-62%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HcG4cLX8TtlHIzC%2B2AsBxxaexbI1C6r2as5aTyaKQaY%3D&st=2019-10-09T19%3A29%3A42Z&se=2019-11-09T19%3A34%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
